using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace UnoPropertyGrid.Generator;

[Generator]
public sealed class PropertyGridDescriptorsGenerator : IIncrementalGenerator
{
    const string AttributeFullName = "UnoPropertyGrid.GeneratePropertyGridDescriptorsAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var typesToGenerate = context.CompilationProvider.Select(CollectTypes);
        context.RegisterSourceOutput(typesToGenerate, Emit);
    }

    static IReadOnlyList<INamedTypeSymbol> CollectTypes(Compilation compilation, System.Threading.CancellationToken ct)
    {
        var attributeSymbol = compilation.GetTypeByMetadataName(AttributeFullName);
        if (attributeSymbol is null)
            return System.Array.Empty<INamedTypeSymbol>();

        var result = new List<INamedTypeSymbol>();
        foreach (var attr in compilation.Assembly.GetAttributes())
        {
            ct.ThrowIfCancellationRequested();
            if (!SymbolEqualityComparer.Default.Equals(attr.AttributeClass, attributeSymbol))
                continue;
            if (attr.ConstructorArguments.Length < 1)
                continue;
            if (attr.ConstructorArguments[0].Value is INamedTypeSymbol typeSymbol)
                result.Add(typeSymbol);
        }
        return result;
    }

    static void Emit(SourceProductionContext ctx, IReadOnlyList<INamedTypeSymbol> types)
    {
        if (types.Count == 0)
            return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("/// <summary>Generated by UnoPropertyGrid.Generator — do not edit.</summary>");
        sb.AppendLine("internal static class GeneratedPropertyGridDescriptors");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Creates a <see cref=\"global::UnoPropertyGrid.LambdaPropertyProvider\"/> pre-configured for all types annotated with <c>[assembly: GeneratePropertyGridDescriptors(...)]</c>.</summary>");
        sb.AppendLine("    public static global::UnoPropertyGrid.LambdaPropertyProvider CreateProvider()");
        sb.AppendLine("    {");
        sb.AppendLine("        var provider = new global::UnoPropertyGrid.LambdaPropertyProvider();");
        foreach (var type in types)
            sb.AppendLine($"        Register{type.Name}(provider);");
        sb.AppendLine("        return provider;");
        sb.AppendLine("    }");
        sb.AppendLine();

        foreach (var type in types)
            EmitRegisterMethod(sb, type, ctx.CancellationToken);

        sb.AppendLine("}");

        ctx.AddSource("GeneratedPropertyGridDescriptors.g.cs",
            SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    static void EmitRegisterMethod(StringBuilder sb, INamedTypeSymbol type, System.Threading.CancellationToken ct)
    {
        var fullTypeName = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var properties = GetBrowsableProperties(type, ct);

        sb.AppendLine($"    static void Register{type.Name}(global::UnoPropertyGrid.LambdaPropertyProvider provider)");
        sb.AppendLine("    {");
        sb.AppendLine($"        provider.Register<{fullTypeName}>(static _c =>");
        sb.AppendLine("            [");
        foreach (var prop in properties)
            EmitDescriptor(sb, prop, fullTypeName);
        sb.AppendLine("            ]);");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    static void EmitDescriptor(StringBuilder sb, IPropertySymbol prop, string componentTypeName)
    {
        var propTypeName = prop.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var category = GetStringArgument(prop, "System.ComponentModel.CategoryAttribute");
        var description = GetStringArgument(prop, "System.ComponentModel.DescriptionAttribute");
        var displayName = GetStringArgument(prop, "System.ComponentModel.DisplayNameAttribute");
        var isExplicitlyReadOnly = GetBoolArgument(prop, "System.ComponentModel.ReadOnlyAttribute");
        var isReadOnly = isExplicitlyReadOnly || prop.SetMethod is null || prop.SetMethod.DeclaredAccessibility != Accessibility.Public;

        var needsBox = prop.Type.IsValueType;

        sb.AppendLine($"                new global::UnoPropertyGrid.PropertyGridPropertyDescriptor(");
        sb.AppendLine($"                    component: _c,");
        sb.AppendLine($"                    name: \"{prop.Name}\",");
        sb.AppendLine($"                    propertyType: typeof({propTypeName}),");

        // getter
        if (needsBox)
            sb.AppendLine($"                    getter: static _c2 => (object?)(({componentTypeName})_c2).{prop.Name},");
        else
            sb.AppendLine($"                    getter: static _c2 => (({componentTypeName})_c2).{prop.Name},");

        // setter
        if (!isReadOnly)
            sb.AppendLine($"                    setter: static (_c2, _v) => (({componentTypeName})_c2).{prop.Name} = ({propTypeName})_v!,");

        if (displayName != null)
            sb.AppendLine($"                    displayName: {Quote(displayName)},");
        if (category != null)
            sb.AppendLine($"                    category: {Quote(category)},");
        if (description != null)
            sb.AppendLine($"                    description: {Quote(description)},");
        if (isReadOnly)
            sb.AppendLine($"                    isReadOnly: true),");
        else
            sb.AppendLine($"                    isReadOnly: false),");
    }

    static IReadOnlyList<IPropertySymbol> GetBrowsableProperties(INamedTypeSymbol type, System.Threading.CancellationToken ct)
    {
        var result = new List<IPropertySymbol>();
        foreach (var member in type.GetMembers())
        {
            ct.ThrowIfCancellationRequested();
            if (member is not IPropertySymbol prop)
                continue;
            if (prop.DeclaredAccessibility != Accessibility.Public)
                continue;
            if (prop.IsStatic)
                continue;
            if (prop.GetMethod is null || prop.GetMethod.DeclaredAccessibility != Accessibility.Public)
                continue;
            if (prop.IsIndexer)
                continue;
            if (IsBrowsableFalse(prop))
                continue;
            result.Add(prop);
        }
        return result;
    }

    static bool IsBrowsableFalse(IPropertySymbol prop)
    {
        foreach (var attr in prop.GetAttributes())
        {
            if (attr.AttributeClass?.ToDisplayString() != "System.ComponentModel.BrowsableAttribute")
                continue;
            if (attr.ConstructorArguments.Length > 0 && attr.ConstructorArguments[0].Value is false)
                return true;
        }
        return false;
    }

    static string? GetStringArgument(IPropertySymbol prop, string attributeFullName)
    {
        foreach (var attr in prop.GetAttributes())
        {
            if (attr.AttributeClass?.ToDisplayString() != attributeFullName)
                continue;
            if (attr.ConstructorArguments.Length > 0 && attr.ConstructorArguments[0].Value is string s)
                return s;
        }
        return null;
    }

    static bool GetBoolArgument(IPropertySymbol prop, string attributeFullName)
    {
        foreach (var attr in prop.GetAttributes())
        {
            if (attr.AttributeClass?.ToDisplayString() != attributeFullName)
                continue;
            if (attr.ConstructorArguments.Length > 0 && attr.ConstructorArguments[0].Value is bool b)
                return b;
        }
        return false;
    }

    static string Quote(string value) =>
        "@\"" + value.Replace("\"", "\"\"") + "\"";
}
