<Project Sdk="Uno.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net9.0-desktop</TargetFrameworks>
    <TargetFrameworks Condition="'$(OS)' == 'Windows_NT'">$(TargetFrameworks);net9.0-windows10.0.19041.0</TargetFrameworks>
    <RootNamespace>UnoPropertyGrid</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <NoWarn>$(NoWarn);1574;1591;8632;UNO0006</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'net9.0-windows10.0.19041.0'">
    <UseWinUI>true</UseWinUI>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <DefineConstants>$(DefineConstants);WINDOWS_APP_SDK</DefineConstants>
    <WindowsSdkPackageVersion>10.0.19041.57</WindowsSdkPackageVersion>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net9.0-windows10.0.19041.0'">
    <PackageReference Include="Microsoft.WindowsAppSDK" />
    <Compile Include="**\*.cs" Exclude="obj\**\*.cs;bin\**\*.cs" />
  </ItemGroup>
</Project>
