<Project Sdk="Uno.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-desktop</TargetFramework>
    <OutputType>Library</OutputType>
    <StartupObject>UnoPropertyGrid.Tests.Program</StartupObject>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <EnableDefaultCompileItems>true</EnableDefaultCompileItems>
    <GenerateTargetPlatformAttribute>false</GenerateTargetPlatformAttribute>
    <GenerateSupportedOSPlatformAttribute>false</GenerateSupportedOSPlatformAttribute>
    <NoWarn>$(NoWarn);CA1416</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnitLite" />
    <PackageReference Include="NUnit3TestAdapter" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\UnoPropertyGrid\UnoPropertyGrid.csproj" />
  </ItemGroup>
</Project>
